### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by sheerun** [bower/bower#1732]
For 1.4 I want to release only few features:

- [x] Add login and unregister commands (#1719)
- [x] Better homedir detection (514eb8f0e38fefeaee6a795a28c277db67adc642)
- [x] Add --save-exact flag #1654
- [x] Ensure extracted files are readable (tar-fs) #1548
- [x] Improved Windows support (AppVeyor CI, tests actually passing on Windows)
- [x] Some minor fixes: #1639, #1620, #1576, #1557, 962a565d3, a464f5a88e
- [x] Automatically detecting smart Git hosts (#1628)
- [x] The version command in the programmatic API now returns the new version (#1755)
- [x] [bower/config#23] Allow npm config variables (#1711)
- [x] [bower/config#24] Merge .bowerrc files upwards directory tree (fixes) #1689

It'll also include greatly improved test coverage (~60% -> ~88%), and many refactors.

I hope it'll break vicious cycle of patch releases.

Things to do before release:

- [x] Finish tests for `bower login` (@sheerun)
- [x] Implement two-factor authentication for login command
- [x] Review diff of all non-test changes (e.g. probably SVNResolver needs some reverting, see #1721)
- [x] Create release draft on GitHub with all changes
- [x] Review of master branch
- [x] Bump package.json to 1.4.0, publish tag on github, and release on npm

@samccone Anything you'd like to add?

**Comment by samccone** [comment]
hey @sheerun let me get all caught up on the notifications and take a look at what you have done.
I think `login and unregister commands` is the last big thing in my mind .. but will come back to this :+1:

**Comment by boxxxie** [comment]
is there a goal of making the user experience with npm better?
mainly thinking about response times for commands and install times.

**Comment by sheerun** [comment]
@samccone @nwinkler @desandro @benschwarz @satazor 

1.4.0 is ready to be released on master branch. Could you review? (especially login / unregister feature, but also other changes mentioned above). I'd like to release tomorrow if you see no issues.

**Comment by sheerun** [comment]
Oh, also @zanona and @kodypeterson

**Comment by sheerun** [comment]
btw. It's more about testing if mentioned features actually work, rather than reviewing the code :)

**Comment by nwinkler** [comment]
Sure - I'll take a look at this today. I'll be testing the #1628 functionality.

**Comment by nwinkler** [comment]
I've tested the #1628 Shallow Cloning option against the following:

* GitHub.com
* BitBucket.org
* Our on-premise Atlassian Stash instance

All three work fine, shallow cloning is enabled automatically for them, based on the server's response.

I don't have access to a GitHub Enterprise instance to verify it against that. Does anyone have access to an instance they could test this with?

When you run `bower install --verbose`, there should be a line like the following for non-GitHub hosts:

```
bower repo#master detect-smart-git Smart Git host detected: true
```

For GitHub Enterprise, it should print `false` instead of `true`, resulting in a full clone, not a shallow one.

**Comment by desandro** [comment]
Success!

+ Able to login with username -> password -> 2FA
+ Unregistered previous package `tap-listener`
+ Registered new package `taplistener` to `git://github.com/metafizzy/tap-listener.git`
+ Unregistered new package `taplistener`
+ Re-registered previous package `tap-listener`

**Comment by samccone** [comment]
:clap: awesome @desandro

**Comment by kodypeterson** [comment]
looks good to me!

**Comment by sheerun** [comment]
Released 1.4.0. Thank you all for support!

**Comment by benschwarz** [comment]
Congrats @sheerun !

**Comment by patrickkettner** [comment]
hurray! freakin awesome work, @sheerun.

**Comment by nwinkler** [comment]
Excellent - thanks, @sheerun!

**Comment by sheerun** [comment]
I've added some of you to release credits. Sorry if I forgot about someone. Thanks again!

**Comment by zanona** [comment]
That's great! thanks a lot @sheerun

**Comment by samccone** [comment]
:clap: amazing work @sheerun :sparkling_heart:
